const dentists=[
  {name:'Yu Ishikawa (Ishi)',role:'Practice owner / lead dentist',photo:'assets/dentist-ishi.jpg',teaser:'BDS Otago 2012. Oral surgery experience from Hutt Hospital, now settled in Alexandra.',bio:'Ishi is the practice owner and lead dentist at Tarbert Street Dental. He brings a calm, thorough approach to every consultation, with particular experience in oral surgery and restorative care.',expertise:['CEREC crowns','Oral surgery','Implants']},
  {name:'Kayla Sleight',role:'Dentist',photo:'assets/dentist-kayla.jpg',teaser:'Raised in Utah, now calls New Zealand home. Particularly good with anxious patients.',bio:'Kayla is passionate about helping patients feel informed and comfortable. Her gentle communication style makes her a wonderful fit for nervous patients and families.',expertise:['Anxious patients','Preventative care','Family dentistry']},
  {name:'Chanelle Gibson',role:'Dentist',photo:'assets/dentist-chanelle.jpg',teaser:'BDS Otago 2019. High-quality care paired with real patient education.',bio:'Chanelle is committed to high-quality care and practical patient education. She enjoys helping people understand their options and feel confident about their treatment.',expertise:['CEREC crowns','Oral surgery','Preventative dentistry']},
  {name:'Bruce Jiang',role:'Dentist',photo:'assets/dentist-bruce.jpg',teaser:'BDS Otago 2022. Thorough consultations and minimally invasive dentistry.',bio:'Bruce values thorough consultations and minimally invasive dentistry. He takes the time to make sure patients feel well informed, comfortable and confident in their care.',expertise:['CEREC crowns','Oral surgery','Minimally invasive care']}
];
const support=[
  {name:'Emma',role:'Dental hygienist / therapist',photo:'assets/staff-emma.jpg',teaser:'A gentle, caring clinician passionate about creating beautiful smiles.',bio:'Emma is passionate about helping create beautiful smiles within the community. She is a gentle and caring clinician with great advice to share with her patients.',expertise:['Hygiene','Oral health advice']},
  {name:'Tori',role:'Dental hygienist / therapist',photo:'assets/staff-tori.jpg',teaser:'Thoughtful preventive care and a calm approach to every clean.',bio:'Tori brings a calm, encouraging approach to preventive care and enjoys helping patients build habits that last.',expertise:['Hygiene','Preventative care']},
  {name:'Mekah',role:'Dental hygienist / therapist',photo:'assets/staff-mekah.jpg',teaser:'Friendly, practical oral health support for the whole family.',bio:'Mekah helps patients of all ages feel comfortable during their hygiene visits and leave with clear, useful advice.',expertise:['Hygiene','Family care']}
];
const card=(member)=>`<article class="person-card"><img src="${member.photo}" alt="${member.name}, ${member.role}" loading="lazy"><div class="person-card-content"><p class="person-role">${member.role}</p><h3>${member.name}</h3><p>${member.teaser}</p></div><button type="button" data-member="${member.name}">View more details</button></article>`;
document.querySelector('[data-dentists]').innerHTML=dentists.map(card).join('');
document.querySelector('[data-support-team]').innerHTML=support.map(card).join('');
const allMembers=[...dentists,...support];const dialog=document.querySelector('[data-bio-dialog]');
const openBio=(name)=>{const member=allMembers.find((item)=>item.name===name);if(!member)return;dialog.querySelector('[data-dialog-image]').src=member.photo;dialog.querySelector('[data-dialog-image]').alt=member.name;dialog.querySelector('[data-dialog-role]').textContent=member.role;dialog.querySelector('[data-dialog-name]').textContent=member.name;dialog.querySelector('[data-dialog-bio]').textContent=member.bio;dialog.querySelector('[data-dialog-expertise]').innerHTML=member.expertise.map((item)=>`<span>${item}</span>`).join('');dialog.showModal()};
document.addEventListener('click',(event)=>{const button=event.target.closest('[data-member]');if(button)openBio(button.dataset.member);if(event.target.matches('[data-dialog-close]'))dialog.close()});
dialog.addEventListener('click',(event)=>{if(event.target===dialog)dialog.close()});document.querySelector('[data-year]').textContent=new Date().getFullYear();
